daemon:
  title: "template backend"
  grpc:
    max_recv_msg_size: 1073741824 # 1GB
    max_send_msg_size: 1073741824 # 1GB
  http:
    host: 0.0.0.0
    port: 5000
    max_call_recv_msg_size: 1073741824 # 1GB
    max_call_send_msg_size: 1073741824 # 1GB
    headers:
      access_control_allow_origins: []
      access_control_allow_origin_wildcard: true
      access_control_max_age: "600"
      cookie_domain: ""
  jwt:
    secret: "NxioXzY4v4IEGdWmIrTG9Ng7Cgo5j3yO" # set in secret
    expiration_time: 72h
    max_refresh_time: 4320h #180d
  jobs:
    job_status_gc:
      enabled: true
  private_key: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEII8kGzWHAJfOs9i/4Itm6XmR/CIb6ePuqx+2waa/U0EuoAoGCCqGSM49
    AwEHoUQDQgAEg3/teKmW70zuiWjYTOynPqPHLOM7XExQUeOD6WSGdlJph3jZzuXh
    f3hlc8rjTTQFa/xIsE+FYdpzVv5TB5qJVw==
    -----END EC PRIVATE KEY-----
  salt: "SNN6lK7wfEHVvN7mAaTI4nH375yQZzV8"
  metrics:
    enabled: false
    authentication:
      enabled: true
      username: prometheus
      password: "" # set in secret
# TODO: refactor storage with the postgresql chart values below
#       to avoid duplication
storage:
  datastores:
    chorus:
      type: postgres
      migration_table_name: tt_migrations
      host: "" # set dynamically in argo-workflows
      port: 5432
      username: admin
      password: password # set in secret
      database: chorus_ci
      max_connections: 10
      max_lifetime: 10s
      debug_mode: true
      ssl:
        enabled: false
        certificate_file: ""
        key_file: ""
  file_stores:
    archive:
      type: minio
      minio_config:
        enabled: false
        endpoint: ""
        access_key_id: ""
        secret_access_key: "" # set in secret
        bucket_name: ""
        use_ssl: false
    disk:
      type: disk
      disk_config:
        enabled: true
        base_path: docker/.diskfilestoreci
services:
  index_service:
    key: value
  authentication_service:
    enabled: true
    dev_auth_enabled: true
    modes:
      internal:
        type: internal
        enabled: true
        public_registration_enabled: false
        button_text: "Login with Chorus"
        icon_url: "data:image/svg+xml;base64,CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBjbGFzcz0ibHVjaWRlIGx1Y2lkZS1hcnJvdy1yaWdodCBtci0yIGgtNCB3LTQiPjxwYXRoIGQ9Ik01IDEyaDE0Ij48L3BhdGg+PHBhdGggZD0ibTEyIDUgNyA3LTcgNyI+PC9wYXRoPjwvc3ZnPgo="
        order: 1
      keycloak:
        type: openid
        enabled: false
        main_source: false
        button_text: "Login with CHUV"
        icon_url: "data:image/svg+xml;base64,CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHN0cm9rZS13aWR0aD0iMiIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBjbGFzcz0ibHVjaWRlIGx1Y2lkZS1hcnJvdy1yaWdodCBtci0yIGgtNCB3LTQiPjxwYXRoIGQ9Ik01IDEyaDE0Ij48L3BhdGg+PHBhdGggZD0ibTEyIDUgNyA3LTcgNyI+PC9wYXRoPjwvc3ZnPgo="
        order: 2
        openid:
          id: keycloak
          chorus_backend_host: ""
          enable_frontend_redirect: true
          chorus_frontend_redirect_url: ""
          authorize_url: ""
          token_url: ""
          user_info_url: ""
          logout_url: ""
          user_name_claim: "preferred_username"
          client_id: chorus
          client_secret: "" # set in secret
          scopes:
            - openid
            - profile
            - email
            - roles
      keycloakdev: {}
  steward:
    init_tenant:
      enabled: false
      tenant_id: 1
    init_user:
      enabled: false
      user_id: 1
      username: chorus
      password: "" # set in secret
      roles:
        - name: Authenticated
          context:
            user: 1
    init_workspace:
      enabled: false
      workspace_id: 1
      name: "Home workspace"
  mailer_service:
    smtp:
      user: smtpUser
      password: "" # set in secret
      host: smtp-relay.sendinblue.com
      port: 587
      authentication: "none"
  workbench_service:
    stream_proxy_enabled: true
    backend_in_k8s: true
    proxy_hit_save_batch_interval: 30s
    workbench_idle_timeout: 504h #21d
  workspace_service:
    enable_kill_fixed_timeout: false
    kill_fixed_timeout: 1h
  # workspace_file_service:
  #   stores:
  #     archive:
  #       client_type: minio
  #       client_name: s3
  #       store_prefix: /workspace-archive
  #       workspace_prefix: "workspaces/%s/data" # %s will be replaced by the namespace name (workspace+id)
  approval_request_service:
    staging_file_store_name: disk
clients:
  docker_client:
    enabled: false
  k8s_client:
    enabled: false
    sa_secret_path: ""
    api_server: ""
    add_user_details: false
log:
  loggers:
    stdout_technical:
      level: debug
    stdout_security:
      level: debug
    stdout_business:
      level: debug
