{{- if .Values.serviceAccount.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.serviceAccountSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "backend.serviceAccountName" . }}
type: kubernetes.io/service-account-token
# TODO: discuss if we really need to use service account token secret
# as seen in the official docs (https://kubernetes.io/docs/concepts/security/service-accounts/#get-a-token)
# this approach is not recommended
{{- end }}
