apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chorus-int-backend
  namespace: argocd
spec:
  project: chorus-int
  destination:
    name: chorus-int
    namespace: backend
  sources:
    - repoURL: https://github.com/CHORUS-TRE/chorus-backend.git
      path: deploy/backend
      targetRevision: HEAD
      helm:
        valueFiles:
          - ../../configs/argoint/values.yaml
        parameters:
          - name: podLabels.commit-sha
            value: $ARGOCD_APP_REVISION_SHORT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - preserveResourcesOnDeletion=true
      - ServerSideApply=false
