apiVersion: v2
name: backend
description: Chorus Backend
type: application
version: 0.3.2
appVersion: 1.16.0

dependencies:
  - name: postgresql
    version: 0.0.19
    repository: oci://harbor.build.chorus-tre.ch/charts
    condition: postgresql.enabled