apiVersion: v2
name: backend
description: Chorus Backend
type: application

# version and appVersion are placeholders and will be overridden
# when packaging the chart for a release
version: 0.0.0
appVersion: 0.0.0

dependencies:
  - name: postgresql
    version: 0.0.19
    repository: oci://harbor.build.chorus-tre.ch/charts
    condition: postgresql.enabled
